// Generated by CoffeeScript 1.4.0
(function() {

  this.Page = (function() {

    function Page(pageName, body) {
      this.pageName = pageName;
      this.body = body;
      this.created = new Date().toString();
      this.saved = "";
    }

    Page.prototype.toString = function() {
      return "" + this.pageName + " \n " + this.body + " \n " + this.created + " \n " + this.saved + " ";
    };

    return Page;

  })();

  this.PageStore = (function() {

    function PageStore() {}

    PageStore.prototype.k = function(pName) {
      return "fpt.pageStore." + pName;
    };

    PageStore.prototype.get = function(pName) {
      var s;
      s = localStorage.getItem(this.k(pName));
      if (s != null) {
        return JSON.parse(s);
      }
      return new Page(pName, initialOpmltext);
    };

    PageStore.prototype.set = function(pName, page) {
      return localStorage.setItem(this.k(pName), JSON.stringify(page));
    };

    PageStore.prototype.save = function(page) {
      page.saved = new Date().toString();
      return this.set(page.pageName, page);
    };

    return PageStore;

  })();

}).call(this);
