// Generated by CoffeeScript 1.4.0
(function() {
  var isSystemService;

  this.Page = (function() {

    function Page(pageName, body) {
      this.pageName = pageName;
      this.body = body;
      this.created = new Date().toString();
      this.saved = "";
      this.text = "";
    }

    Page.prototype.toString = function() {
      return "" + this.pageName + " \n " + this.body + " \n " + this.created + " \n " + this.saved + " ";
    };

    return Page;

  })();

  isSystemService = function(name) {
    return name.search("!!") > -1;
  };

  this.DummyPageStore = (function() {

    function DummyPageStore() {}

    DummyPageStore.prototype.hasName = function(pName) {
      return false;
    };

    DummyPageStore.prototype.hasSystemService = function(pName) {
      return false;
    };

    DummyPageStore.prototype.get = function(pName, callback) {
      return callback(new Page(pName, initialOpmltext));
    };

    DummyPageStore.prototype.save = function(page, errorCallback) {};

    return DummyPageStore;

  })();

  this.BrowserBasedPageStore = (function() {

    function BrowserBasedPageStore() {}

    BrowserBasedPageStore.prototype.k = function(pName) {
      return "fpt.pageStore." + pName;
    };

    BrowserBasedPageStore.prototype.x = function(pName) {
      return "fpt.ps.X." + pName;
    };

    BrowserBasedPageStore.prototype.isDirty = function(pName) {
      var s;
      s = localStorage.getItem(this.x(pName));
      return s === "true";
    };

    BrowserBasedPageStore.prototype.setDirty = function(pName) {
      return localStorage.setItem(this.x(pName), "true");
    };

    BrowserBasedPageStore.prototype.setClean = function(pName) {
      return localStorage.setItem(this.x(pName), "false");
    };

    BrowserBasedPageStore.prototype.hasName = function(pName) {
      var s;
      s = localStorage.getItem(this.k(pName));
      if (s != null) {
        return true;
      }
      return false;
    };

    BrowserBasedPageStore.prototype.hasSystemService = function(pName) {
      return false;
    };

    BrowserBasedPageStore.prototype.get = function(pName, callback) {
      var page, s;
      s = localStorage.getItem(this.k(pName));
      if (s != null) {
        page = JSON.parse(s);
      } else {
        page = new Page(pName, initialOpmltext);
      }
      return callback(page);
    };

    BrowserBasedPageStore.prototype.set = function(pName, page) {
      localStorage.setItem(this.k(pName), JSON.stringify(page));
      return this.setDirty(pName);
    };

    BrowserBasedPageStore.prototype.save = function(page, errorCallback) {
      if (isSystemService(page.pageName)) {
        return;
      }
      page.saved = new Date().toString();
      return this.set(page.pageName, page);
    };

    return BrowserBasedPageStore;

  })();

  this.ServerBasedPageStore = (function() {

    function ServerBasedPageStore(getUrl, postUrl, postSuccessHandler) {
      this.getUrl = getUrl;
      this.postUrl = postUrl;
      this.postSuccessHandler = postSuccessHandler;
    }

    ServerBasedPageStore.prototype.get = function(pName, callback) {
      var _this = this;
      return $.ajax({
        type: 'GET',
        url: this.getUrl + pName,
        success: function(data) {
          var msg, x;
          x = $($.parseXML(data.toLowerCase())).find('message')[0];
          msg = "";
          if (x) {
            msg = x["textContent"];
          }
          if (msg === "missing file") {
            console.log("Page " + pName + " doesn't exist so creating");
            return callback(new Page(pName, initialOpmltext));
          } else {
            return callback(new Page(pName, data));
          }
        },
        error: function(response) {
          console.log("ERROR IN get " + pName);
          return console.log(response);
        }
      });
    };

    ServerBasedPageStore.prototype.save = function(page, saveErrorHandler) {
      var _this = this;
      if (isSystemService(page.pageName)) {
        return;
      }
      return $.ajax({
        type: 'POST',
        url: this.postUrl + page.pageName,
        data: {
          "pageName": page.pageName,
          "body": page.body,
          "text": page.text
        },
        success: function(data) {
          return _this.postSuccessHandler(page.pageName);
        },
        error: function(xmlHttpRequest) {
          console.log("ERROR IN POST " + page.pageName);
          console.log(xmlHttpRequest);
          return saveErrorHandler(xmlHttpRequest);
        }
      });
    };

    return ServerBasedPageStore;

  })();

  this.AndroidBasedPageStore = (function() {

    function AndroidBasedPageStore() {}

    AndroidBasedPageStore.prototype.hasName = function(pName) {
      var s;
      s = Android.readPage(pName);
      if (s === "NO FILE") {
        return false;
      }
      return true;
    };

    AndroidBasedPageStore.prototype.get = function(pName, callback) {
      var page, s;
      console.log("trying to read " + pName + " from Android");
      s = Android.readPage(pName);
      console.log("Android read " + pName);
      console.log(s);
      if (s === "NO FILE") {
        page = new Page(pName, initialOpmltext);
      } else {
        page = new Page(pName, s);
      }
      console.log(page);
      return callback(page);
    };

    AndroidBasedPageStore.prototype.save = function(page, errorCallback) {
      var s;
      s = Android.writePage(page.pageName, page.body);
      if (s !== "OK") {
        return errorCallback(s);
      }
    };

    return AndroidBasedPageStore;

  })();

}).call(this);
